-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, date_format(DATE_OF_BIRTH,"%Y-%m-%d") as DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER = "W" and MONTH(DATE_OF_BIRTH) = 3 and NOT TLNO IS NULL
ORDER BY MEMBER_ID